/**
 * Maheta API - OpenAPI 3.0
 * This is api for MS translator services
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LanguageDto {
  name?: string;
  code?: string;
  scriptCodes?: Array<string>;
}
